const EC = require('elliptic').ec;
const ec = EC('secp256k1');
const { Transaction } = require('../services/transaction');
const { Blockchain } = require('../services/blockChain');

export const initChain = new Blockchain();

// generated by key generator
const myKey = ec.keyFromPrivate('079428c87bbf98b5dadf1ad971f721c8ea5a6aef865f1ece3f6ccece081d31cc');
// const walletAddress = myKey.getPublic('hex');

export const addTransaction = (trans) => {
  const transaction = new Transaction(trans.from, trans.to, trans.amount);
  transaction.signTransaction(myKey);
  initChain.addTransaction(transaction);
}
